# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bms_dids_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bms_dids_msg.proto',
  package='',
  serialized_pb=_b('\n\x12\x62ms_dids_msg.proto\"Y\n\x0b\x42MSDIDEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12\x1a\n\x08\x64id_info\x18\x04 \x03(\x0b\x32\x08.DIDInfo\"$\n\x07\x44IDInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB7\n$com.nextev.cvs_proto.protobuf.eventsB\rBMSDIDMessageH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BMSDIDEVENT = _descriptor.Descriptor(
  name='BMSDIDEvent',
  full_name='BMSDIDEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BMSDIDEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='BMSDIDEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='BMSDIDEvent.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='did_info', full_name='BMSDIDEvent.did_info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=111,
)


_DIDINFO = _descriptor.Descriptor(
  name='DIDInfo',
  full_name='DIDInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DIDInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DIDInfo.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=149,
)

_BMSDIDEVENT.fields_by_name['did_info'].message_type = _DIDINFO
DESCRIPTOR.message_types_by_name['BMSDIDEvent'] = _BMSDIDEVENT
DESCRIPTOR.message_types_by_name['DIDInfo'] = _DIDINFO

BMSDIDEvent = _reflection.GeneratedProtocolMessageType('BMSDIDEvent', (_message.Message,), dict(
  DESCRIPTOR = _BMSDIDEVENT,
  __module__ = 'bms_dids_msg_pb2'
  # @@protoc_insertion_point(class_scope:BMSDIDEvent)
  ))
_sym_db.RegisterMessage(BMSDIDEvent)

DIDInfo = _reflection.GeneratedProtocolMessageType('DIDInfo', (_message.Message,), dict(
  DESCRIPTOR = _DIDINFO,
  __module__ = 'bms_dids_msg_pb2'
  # @@protoc_insertion_point(class_scope:DIDInfo)
  ))
_sym_db.RegisterMessage(DIDInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\rBMSDIDMessageH\003'))
# @@protoc_insertion_point(module_scope)
