# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='can_msg.proto',
  package='',
  serialized_pb=_b('\n\rcan_msg.proto\"\xa2\x01\n\x06\x43\x61nMsg\x12!\n\x08\x63\x61n_data\x18\x01 \x03(\x0b\x32\x0f.CanMsg.CanData\x12!\n\x08\x63\x61n_news\x18\x02 \x03(\x0b\x32\x0f.CanMsg.CanNews\x1a(\n\x07\x43\x61nData\x12\x0e\n\x06msg_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c\x1a(\n\x07\x43\x61nNews\x12\x0e\n\x06msg_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x03(\x0c\x42\x32\n$com.nextev.cvs_proto.protobuf.customB\nCanMsgUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CANMSG_CANDATA = _descriptor.Descriptor(
  name='CanData',
  full_name='CanMsg.CanData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='CanMsg.CanData.msg_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='CanMsg.CanData.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=138,
)

_CANMSG_CANNEWS = _descriptor.Descriptor(
  name='CanNews',
  full_name='CanMsg.CanNews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='CanMsg.CanNews.msg_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='CanMsg.CanNews.value', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=180,
)

_CANMSG = _descriptor.Descriptor(
  name='CanMsg',
  full_name='CanMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='can_data', full_name='CanMsg.can_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_news', full_name='CanMsg.can_news', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CANMSG_CANDATA, _CANMSG_CANNEWS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=180,
)

_CANMSG_CANDATA.containing_type = _CANMSG
_CANMSG_CANNEWS.containing_type = _CANMSG
_CANMSG.fields_by_name['can_data'].message_type = _CANMSG_CANDATA
_CANMSG.fields_by_name['can_news'].message_type = _CANMSG_CANNEWS
DESCRIPTOR.message_types_by_name['CanMsg'] = _CANMSG

CanMsg = _reflection.GeneratedProtocolMessageType('CanMsg', (_message.Message,), dict(

  CanData = _reflection.GeneratedProtocolMessageType('CanData', (_message.Message,), dict(
    DESCRIPTOR = _CANMSG_CANDATA,
    __module__ = 'can_msg_pb2'
    # @@protoc_insertion_point(class_scope:CanMsg.CanData)
    ))
  ,

  CanNews = _reflection.GeneratedProtocolMessageType('CanNews', (_message.Message,), dict(
    DESCRIPTOR = _CANMSG_CANNEWS,
    __module__ = 'can_msg_pb2'
    # @@protoc_insertion_point(class_scope:CanMsg.CanNews)
    ))
  ,
  DESCRIPTOR = _CANMSG,
  __module__ = 'can_msg_pb2'
  # @@protoc_insertion_point(class_scope:CanMsg)
  ))
_sym_db.RegisterMessage(CanMsg)
_sym_db.RegisterMessage(CanMsg.CanData)
_sym_db.RegisterMessage(CanMsg.CanNews)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.customB\nCanMsgUnit'))
# @@protoc_insertion_point(module_scope)
