# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can_signal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='can_signal.proto',
  package='',
  serialized_pb=_b('\n\x10\x63\x61n_signal.proto\"\xb9\x01\n\tCanSignal\x12\x11\n\tsample_ts\x18\x01 \x01(\x04\x12*\n\x0bsignal_info\x18\x02 \x03(\x0b\x32\x15.CanSignal.SignalInfo\x1a@\n\nSignalInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12&\n\tdata_info\x18\x02 \x03(\x0b\x32\x13.CanSignal.DataInfo\x1a+\n\x08\x44\x61taInfo\x12\x11\n\tts_offset\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x35\n$com.nextev.cvs_proto.protobuf.customB\rCanSignalUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CANSIGNAL_SIGNALINFO = _descriptor.Descriptor(
  name='SignalInfo',
  full_name='CanSignal.SignalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CanSignal.SignalInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_info', full_name='CanSignal.SignalInfo.data_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=161,
)

_CANSIGNAL_DATAINFO = _descriptor.Descriptor(
  name='DataInfo',
  full_name='CanSignal.DataInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts_offset', full_name='CanSignal.DataInfo.ts_offset', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='CanSignal.DataInfo.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=206,
)

_CANSIGNAL = _descriptor.Descriptor(
  name='CanSignal',
  full_name='CanSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='CanSignal.sample_ts', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_info', full_name='CanSignal.signal_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CANSIGNAL_SIGNALINFO, _CANSIGNAL_DATAINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=206,
)

_CANSIGNAL_SIGNALINFO.fields_by_name['data_info'].message_type = _CANSIGNAL_DATAINFO
_CANSIGNAL_SIGNALINFO.containing_type = _CANSIGNAL
_CANSIGNAL_DATAINFO.containing_type = _CANSIGNAL
_CANSIGNAL.fields_by_name['signal_info'].message_type = _CANSIGNAL_SIGNALINFO
DESCRIPTOR.message_types_by_name['CanSignal'] = _CANSIGNAL

CanSignal = _reflection.GeneratedProtocolMessageType('CanSignal', (_message.Message,), dict(

  SignalInfo = _reflection.GeneratedProtocolMessageType('SignalInfo', (_message.Message,), dict(
    DESCRIPTOR = _CANSIGNAL_SIGNALINFO,
    __module__ = 'can_signal_pb2'
    # @@protoc_insertion_point(class_scope:CanSignal.SignalInfo)
    ))
  ,

  DataInfo = _reflection.GeneratedProtocolMessageType('DataInfo', (_message.Message,), dict(
    DESCRIPTOR = _CANSIGNAL_DATAINFO,
    __module__ = 'can_signal_pb2'
    # @@protoc_insertion_point(class_scope:CanSignal.DataInfo)
    ))
  ,
  DESCRIPTOR = _CANSIGNAL,
  __module__ = 'can_signal_pb2'
  # @@protoc_insertion_point(class_scope:CanSignal)
  ))
_sym_db.RegisterMessage(CanSignal)
_sym_db.RegisterMessage(CanSignal.SignalInfo)
_sym_db.RegisterMessage(CanSignal.DataInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.customB\rCanSignalUnit'))
# @@protoc_insertion_point(module_scope)
