# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cdc_err_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cdc_err_msg.proto',
  package='',
  serialized_pb=_b('\n\x11\x63\x64\x63_err_msg.proto\"^\n\x13\x43\x44\x43SystemErrorEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12\x17\n\x0f\x63\x61n_cdc_sys_err\x18\x04 \x01(\x05\x42=\n$com.nextev.cvs_proto.protobuf.eventsB\x15\x43\x44\x43SystemErrorMessage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CDCSYSTEMERROREVENT = _descriptor.Descriptor(
  name='CDCSystemErrorEvent',
  full_name='CDCSystemErrorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CDCSystemErrorEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='CDCSystemErrorEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='CDCSystemErrorEvent.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_cdc_sys_err', full_name='CDCSystemErrorEvent.can_cdc_sys_err', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['CDCSystemErrorEvent'] = _CDCSYSTEMERROREVENT

CDCSystemErrorEvent = _reflection.GeneratedProtocolMessageType('CDCSystemErrorEvent', (_message.Message,), dict(
  DESCRIPTOR = _CDCSYSTEMERROREVENT,
  __module__ = 'cdc_err_msg_pb2'
  # @@protoc_insertion_point(class_scope:CDCSystemErrorEvent)
  ))
_sym_db.RegisterMessage(CDCSystemErrorEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\025CDCSystemErrorMessage'))
# @@protoc_insertion_point(module_scope)
