# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection_status_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vehicle_status_pb2
import position_status_pb2
import soc_status_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='connection_status_message.proto',
  package='',
  serialized_pb=_b('\n\x1f\x63onnection_status_message.proto\x1a\x14vehicle_status.proto\x1a\x15position_status.proto\x1a\x10soc_status.proto\"\xe6\x03\n\x13\x43onnectionStatusMsg\x12\x0b\n\x03vid\x18\x01 \x01(\t\x12\x11\n\tsample_ts\x18\x02 \x01(\x04\x12@\n\x11\x63onnection_status\x18\x03 \x01(\x0b\x32%.ConnectionStatusMsg.connectionStatus\x12\x12\n\nprocess_id\x18\x04 \x01(\t\x12(\n\x0fposition_status\x18\x05 \x01(\x0b\x32\x0f.PositionStatus\x12&\n\x0evehicle_status\x18\x06 \x01(\x0b\x32\x0e.VehicleStatus\x12\x1e\n\nsoc_status\x18\x07 \x01(\x0b\x32\n.SOCStatus\x1a\x88\x01\n\x10\x63onnectionStatus\x12.\n\x08\x65\x63u_type\x18\x01 \x01(\x0e\x32\x1c.ConnectionStatusMsg.EcuType\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.ConnectionStatusMsg.Status\x12\x17\n\x0flatest_msg_type\x18\x03 \x01(\t\"$\n\x07\x45\x63uType\x12\x07\n\x03\x43GW\x10\x00\x12\x07\n\x03\x43\x44\x43\x10\x01\x12\x07\n\x03\x41\x44\x43\x10\x02\"6\n\x06Status\x12\x0b\n\x07OFFLINE\x10\x00\x12\n\n\x06ONLINE\x10\x01\x12\x13\n\x0f\x43ONNECTION_LOST\x10\x02\x42?\n$com.nextev.cvs_proto.protobuf.eventsB\x17\x43onnectionStatusMessage')
  ,
  dependencies=[vehicle_status_pb2.DESCRIPTOR,position_status_pb2.DESCRIPTOR,soc_status_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONNECTIONSTATUSMSG_ECUTYPE = _descriptor.EnumDescriptor(
  name='EcuType',
  full_name='ConnectionStatusMsg.EcuType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CGW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CDC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADC', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=493,
  serialized_end=529,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONSTATUSMSG_ECUTYPE)

_CONNECTIONSTATUSMSG_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ConnectionStatusMsg.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_LOST', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=531,
  serialized_end=585,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONSTATUSMSG_STATUS)


_CONNECTIONSTATUSMSG_CONNECTIONSTATUS = _descriptor.Descriptor(
  name='connectionStatus',
  full_name='ConnectionStatusMsg.connectionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ecu_type', full_name='ConnectionStatusMsg.connectionStatus.ecu_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='ConnectionStatusMsg.connectionStatus.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latest_msg_type', full_name='ConnectionStatusMsg.connectionStatus.latest_msg_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=491,
)

_CONNECTIONSTATUSMSG = _descriptor.Descriptor(
  name='ConnectionStatusMsg',
  full_name='ConnectionStatusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vid', full_name='ConnectionStatusMsg.vid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='ConnectionStatusMsg.sample_ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connection_status', full_name='ConnectionStatusMsg.connection_status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='ConnectionStatusMsg.process_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_status', full_name='ConnectionStatusMsg.position_status', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_status', full_name='ConnectionStatusMsg.vehicle_status', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soc_status', full_name='ConnectionStatusMsg.soc_status', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CONNECTIONSTATUSMSG_CONNECTIONSTATUS, ],
  enum_types=[
    _CONNECTIONSTATUSMSG_ECUTYPE,
    _CONNECTIONSTATUSMSG_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=585,
)

_CONNECTIONSTATUSMSG_CONNECTIONSTATUS.fields_by_name['ecu_type'].enum_type = _CONNECTIONSTATUSMSG_ECUTYPE
_CONNECTIONSTATUSMSG_CONNECTIONSTATUS.fields_by_name['status'].enum_type = _CONNECTIONSTATUSMSG_STATUS
_CONNECTIONSTATUSMSG_CONNECTIONSTATUS.containing_type = _CONNECTIONSTATUSMSG
_CONNECTIONSTATUSMSG.fields_by_name['connection_status'].message_type = _CONNECTIONSTATUSMSG_CONNECTIONSTATUS
_CONNECTIONSTATUSMSG.fields_by_name['position_status'].message_type = position_status_pb2._POSITIONSTATUS
_CONNECTIONSTATUSMSG.fields_by_name['vehicle_status'].message_type = vehicle_status_pb2._VEHICLESTATUS
_CONNECTIONSTATUSMSG.fields_by_name['soc_status'].message_type = soc_status_pb2._SOCSTATUS
_CONNECTIONSTATUSMSG_ECUTYPE.containing_type = _CONNECTIONSTATUSMSG
_CONNECTIONSTATUSMSG_STATUS.containing_type = _CONNECTIONSTATUSMSG
DESCRIPTOR.message_types_by_name['ConnectionStatusMsg'] = _CONNECTIONSTATUSMSG

ConnectionStatusMsg = _reflection.GeneratedProtocolMessageType('ConnectionStatusMsg', (_message.Message,), dict(

  connectionStatus = _reflection.GeneratedProtocolMessageType('connectionStatus', (_message.Message,), dict(
    DESCRIPTOR = _CONNECTIONSTATUSMSG_CONNECTIONSTATUS,
    __module__ = 'connection_status_message_pb2'
    # @@protoc_insertion_point(class_scope:ConnectionStatusMsg.connectionStatus)
    ))
  ,
  DESCRIPTOR = _CONNECTIONSTATUSMSG,
  __module__ = 'connection_status_message_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionStatusMsg)
  ))
_sym_db.RegisterMessage(ConnectionStatusMsg)
_sym_db.RegisterMessage(ConnectionStatusMsg.connectionStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\027ConnectionStatusMessage'))
# @@protoc_insertion_point(module_scope)
