# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: did_update_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import did_data_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='did_update_msg.proto',
  package='',
  serialized_pb=_b('\n\x14\x64id_update_msg.proto\x1a\x0e\x64id_data.proto\"n\n\x0e\x44IDUpdateEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0f\n\x07\x64id_tag\x18\x03 \x01(\t\x12\x12\n\ncommand_id\x18\x04 \x01(\t\x12\x1a\n\x08\x64id_data\x18\x05 \x03(\x0b\x32\x08.DIDDataB8\n$com.nextev.cvs_proto.protobuf.eventsB\x10\x44IDUpdateMessage')
  ,
  dependencies=[did_data_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIDUPDATEEVENT = _descriptor.Descriptor(
  name='DIDUpdateEvent',
  full_name='DIDUpdateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DIDUpdateEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='DIDUpdateEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='did_tag', full_name='DIDUpdateEvent.did_tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command_id', full_name='DIDUpdateEvent.command_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='did_data', full_name='DIDUpdateEvent.did_data', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=150,
)

_DIDUPDATEEVENT.fields_by_name['did_data'].message_type = did_data_pb2._DIDDATA
DESCRIPTOR.message_types_by_name['DIDUpdateEvent'] = _DIDUPDATEEVENT

DIDUpdateEvent = _reflection.GeneratedProtocolMessageType('DIDUpdateEvent', (_message.Message,), dict(
  DESCRIPTOR = _DIDUPDATEEVENT,
  __module__ = 'did_update_msg_pb2'
  # @@protoc_insertion_point(class_scope:DIDUpdateEvent)
  ))
_sym_db.RegisterMessage(DIDUpdateEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\020DIDUpdateMessage'))
# @@protoc_insertion_point(module_scope)
