# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: did_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='did_data.proto',
  package='',
  serialized_pb=_b('\n\x0e\x64id_data.proto\"y\n\x07\x44IDData\x12\x0b\n\x03\x65\x63u\x18\x01 \x01(\t\x12\x1a\n\x04\x64ids\x18\x02 \x03(\x0b\x32\x0c.DIDData.DID\x1a\x45\n\x03\x44ID\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12\x10\n\x08\x65rr_code\x18\x04 \x01(\x05\x42\x33\n$com.nextev.cvs_proto.protobuf.customB\x0b\x44IDDataUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIDDATA_DID = _descriptor.Descriptor(
  name='DID',
  full_name='DIDData.DID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DIDData.DID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DIDData.DID.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='DIDData.DID.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='DIDData.DID.err_code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=139,
)

_DIDDATA = _descriptor.Descriptor(
  name='DIDData',
  full_name='DIDData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ecu', full_name='DIDData.ecu', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dids', full_name='DIDData.dids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DIDDATA_DID, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=139,
)

_DIDDATA_DID.containing_type = _DIDDATA
_DIDDATA.fields_by_name['dids'].message_type = _DIDDATA_DID
DESCRIPTOR.message_types_by_name['DIDData'] = _DIDDATA

DIDData = _reflection.GeneratedProtocolMessageType('DIDData', (_message.Message,), dict(

  DID = _reflection.GeneratedProtocolMessageType('DID', (_message.Message,), dict(
    DESCRIPTOR = _DIDDATA_DID,
    __module__ = 'did_data_pb2'
    # @@protoc_insertion_point(class_scope:DIDData.DID)
    ))
  ,
  DESCRIPTOR = _DIDDATA,
  __module__ = 'did_data_pb2'
  # @@protoc_insertion_point(class_scope:DIDData)
  ))
_sym_db.RegisterMessage(DIDData)
_sym_db.RegisterMessage(DIDData.DID)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.customB\013DIDDataUnit'))
# @@protoc_insertion_point(module_scope)
