# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evm_param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='evm_param.proto',
  package='',
  serialized_pb=_b('\n\x0f\x65vm_param.proto\"\xb5\x03\n\x08\x45vmParam\x12\x1e\n\x16vehl_storage_period_ms\x18\x01 \x01(\x05\x12 \n\x18normal_report_period_sec\x18\x02 \x01(\x05\x12\x1e\n\x16\x61larm_report_period_ms\x18\x03 \x01(\x05\x12\x18\n\x10hardware_version\x18\x04 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x05 \x01(\t\x12!\n\x19vehl_heartbeat_period_sec\x18\x06 \x01(\x05\x12\x1e\n\x16login_delay_aft3_fails\x18\x07 \x01(\x05\x12\x19\n\x11vehl_resp_timeout\x18\x08 \x01(\x05\x12\x1d\n\x15platform_resp_timeout\x18\t \x01(\x05\x12\x18\n\x10gb_platform_host\x18\n \x01(\t\x12\x18\n\x10gb_platform_port\x18\x0b \x01(\x05\x12\x1e\n\x16in_sampling_inspection\x18\x0c \x01(\x08\x12\x18\n\x10sample_period_ms\x18\r \x01(\x05\"(\n\x0ePosngValidType\x12\t\n\x05VALID\x10\x00\x12\x0b\n\x07INVALID\x10\x01\x42\x33\n#com.nextev.cvs_proto.protobuf.gb_dbB\x0c\x45vmParamUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_EVMPARAM_POSNGVALIDTYPE = _descriptor.EnumDescriptor(
  name='PosngValidType',
  full_name='EvmParam.PosngValidType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=417,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_EVMPARAM_POSNGVALIDTYPE)


_EVMPARAM = _descriptor.Descriptor(
  name='EvmParam',
  full_name='EvmParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehl_storage_period_ms', full_name='EvmParam.vehl_storage_period_ms', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normal_report_period_sec', full_name='EvmParam.normal_report_period_sec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_report_period_ms', full_name='EvmParam.alarm_report_period_ms', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_version', full_name='EvmParam.hardware_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmware_version', full_name='EvmParam.firmware_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehl_heartbeat_period_sec', full_name='EvmParam.vehl_heartbeat_period_sec', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='login_delay_aft3_fails', full_name='EvmParam.login_delay_aft3_fails', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehl_resp_timeout', full_name='EvmParam.vehl_resp_timeout', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform_resp_timeout', full_name='EvmParam.platform_resp_timeout', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gb_platform_host', full_name='EvmParam.gb_platform_host', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gb_platform_port', full_name='EvmParam.gb_platform_port', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_sampling_inspection', full_name='EvmParam.in_sampling_inspection', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_period_ms', full_name='EvmParam.sample_period_ms', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVMPARAM_POSNGVALIDTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=457,
)

_EVMPARAM_POSNGVALIDTYPE.containing_type = _EVMPARAM
DESCRIPTOR.message_types_by_name['EvmParam'] = _EVMPARAM

EvmParam = _reflection.GeneratedProtocolMessageType('EvmParam', (_message.Message,), dict(
  DESCRIPTOR = _EVMPARAM,
  __module__ = 'evm_param_pb2'
  # @@protoc_insertion_point(class_scope:EvmParam)
  ))
_sym_db.RegisterMessage(EvmParam)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.nextev.cvs_proto.protobuf.gb_dbB\014EvmParamUnit'))
# @@protoc_insertion_point(module_scope)
