# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature_status_update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import position_status_pb2
import feature_status_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature_status_update.proto',
  package='',
  serialized_pb=_b('\n\x1b\x66\x65\x61ture_status_update.proto\x1a\x15position_status.proto\x1a\x14\x66\x65\x61ture_status.proto\"s\n\x13\x46\x65\x61tureStatusUpdate\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.PositionStatus\x12&\n\x0e\x66\x65\x61ture_status\x18\x02 \x01(\x0b\x32\x0e.FeatureStatus\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x42=\n\"com.nextev.cvs_proto.protobuf.adasB\x17\x46\x65\x61tureStatusUpdateUnit')
  ,
  dependencies=[position_status_pb2.DESCRIPTOR,feature_status_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEATURESTATUSUPDATE = _descriptor.Descriptor(
  name='FeatureStatusUpdate',
  full_name='FeatureStatusUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='FeatureStatusUpdate.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_status', full_name='FeatureStatusUpdate.feature_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FeatureStatusUpdate.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=191,
)

_FEATURESTATUSUPDATE.fields_by_name['position'].message_type = position_status_pb2._POSITIONSTATUS
_FEATURESTATUSUPDATE.fields_by_name['feature_status'].message_type = feature_status_pb2._FEATURESTATUS
DESCRIPTOR.message_types_by_name['FeatureStatusUpdate'] = _FEATURESTATUSUPDATE

FeatureStatusUpdate = _reflection.GeneratedProtocolMessageType('FeatureStatusUpdate', (_message.Message,), dict(
  DESCRIPTOR = _FEATURESTATUSUPDATE,
  __module__ = 'feature_status_update_pb2'
  # @@protoc_insertion_point(class_scope:FeatureStatusUpdate)
  ))
_sym_db.RegisterMessage(FeatureStatusUpdate)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.nextev.cvs_proto.protobuf.adasB\027FeatureStatusUpdateUnit'))
# @@protoc_insertion_point(module_scope)
