# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: low_soc_range.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='low_soc_range.proto',
  package='',
  serialized_pb=_b('\n\x13low_soc_range.proto\"h\n\x0bLowSocRange\x12+\n\x0elow_soc_status\x18\x01 \x01(\x0e\x32\x13.LowSocRange.Status\",\n\x06Status\x12\r\n\tNO_SIGNAL\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x07\n\x03RED\x10\x02\x42\x34\n!com.nextev.cvs_proto.protobuf.cdcB\x0fLowSocRangeUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LOWSOCRANGE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='LowSocRange.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_SIGNAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=83,
  serialized_end=127,
)
_sym_db.RegisterEnumDescriptor(_LOWSOCRANGE_STATUS)


_LOWSOCRANGE = _descriptor.Descriptor(
  name='LowSocRange',
  full_name='LowSocRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='low_soc_status', full_name='LowSocRange.low_soc_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOWSOCRANGE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=127,
)

_LOWSOCRANGE.fields_by_name['low_soc_status'].enum_type = _LOWSOCRANGE_STATUS
_LOWSOCRANGE_STATUS.containing_type = _LOWSOCRANGE
DESCRIPTOR.message_types_by_name['LowSocRange'] = _LOWSOCRANGE

LowSocRange = _reflection.GeneratedProtocolMessageType('LowSocRange', (_message.Message,), dict(
  DESCRIPTOR = _LOWSOCRANGE,
  __module__ = 'low_soc_range_pb2'
  # @@protoc_insertion_point(class_scope:LowSocRange)
  ))
_sym_db.RegisterMessage(LowSocRange)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.nextev.cvs_proto.protobuf.cdcB\017LowSocRangeUnit'))
# @@protoc_insertion_point(module_scope)
