# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: low_soc_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import low_soc_range_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='low_soc_event.proto',
  package='',
  serialized_pb=_b('\n\x13low_soc_event.proto\x1a\x13low_soc_range.proto\"b\n\x0bLowSocEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12#\n\rlow_soc_range\x18\x04 \x01(\x0b\x32\x0c.LowSocRangeB2\n!com.nextev.cvs_proto.protobuf.cdcB\rLowSocMessage')
  ,
  dependencies=[low_soc_range_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOWSOCEVENT = _descriptor.Descriptor(
  name='LowSocEvent',
  full_name='LowSocEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LowSocEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='LowSocEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='LowSocEvent.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_soc_range', full_name='LowSocEvent.low_soc_range', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=142,
)

_LOWSOCEVENT.fields_by_name['low_soc_range'].message_type = low_soc_range_pb2._LOWSOCRANGE
DESCRIPTOR.message_types_by_name['LowSocEvent'] = _LOWSOCEVENT

LowSocEvent = _reflection.GeneratedProtocolMessageType('LowSocEvent', (_message.Message,), dict(
  DESCRIPTOR = _LOWSOCEVENT,
  __module__ = 'low_soc_event_pb2'
  # @@protoc_insertion_point(class_scope:LowSocEvent)
  ))
_sym_db.RegisterMessage(LowSocEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.nextev.cvs_proto.protobuf.cdcB\rLowSocMessage'))
# @@protoc_insertion_point(module_scope)
