# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lv_batt_charging_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vehicle_status_pb2
import can_msg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lv_batt_charging_msg.proto',
  package='',
  serialized_pb=_b('\n\x1alv_batt_charging_msg.proto\x1a\x14vehicle_status.proto\x1a\rcan_msg.proto\"\x84\x02\n\x13LvBattChargingEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\x04\x12\x11\n\tevent_num\x18\x05 \x01(\x05\x12\x17\n\x0f\x63gw_log_voltage\x18\x06 \x01(\x02\x12\x13\n\x0b\x63gw_log_soc\x18\x07 \x01(\x02\x12&\n\x0evehicle_status\x18\x08 \x01(\x0b\x32\x0e.VehicleStatus\x12\x18\n\x07\x63\x61n_msg\x18\t \x01(\x0b\x32\x07.CanMsg\x12(\n\x10pre_cgw_log_info\x18\n \x03(\x0b\x32\x0e.PreCgwLogInfo\"Q\n\rPreCgwLogInfo\x12\x11\n\tsample_ts\x18\x01 \x01(\x04\x12\x18\n\x10\x63gw_log_volatage\x18\x02 \x01(\x02\x12\x13\n\x0b\x63gw_log_soc\x18\x03 \x01(\x02\x42=\n$com.nextev.cvs_proto.protobuf.eventsB\x15LvBattChargingMessage')
  ,
  dependencies=[vehicle_status_pb2.DESCRIPTOR,can_msg_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LVBATTCHARGINGEVENT = _descriptor.Descriptor(
  name='LvBattChargingEvent',
  full_name='LvBattChargingEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LvBattChargingEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='LvBattChargingEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='LvBattChargingEvent.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='LvBattChargingEvent.event_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_num', full_name='LvBattChargingEvent.event_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgw_log_voltage', full_name='LvBattChargingEvent.cgw_log_voltage', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgw_log_soc', full_name='LvBattChargingEvent.cgw_log_soc', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_status', full_name='LvBattChargingEvent.vehicle_status', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_msg', full_name='LvBattChargingEvent.can_msg', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre_cgw_log_info', full_name='LvBattChargingEvent.pre_cgw_log_info', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=328,
)


_PRECGWLOGINFO = _descriptor.Descriptor(
  name='PreCgwLogInfo',
  full_name='PreCgwLogInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='PreCgwLogInfo.sample_ts', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgw_log_volatage', full_name='PreCgwLogInfo.cgw_log_volatage', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgw_log_soc', full_name='PreCgwLogInfo.cgw_log_soc', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=411,
)

_LVBATTCHARGINGEVENT.fields_by_name['vehicle_status'].message_type = vehicle_status_pb2._VEHICLESTATUS
_LVBATTCHARGINGEVENT.fields_by_name['can_msg'].message_type = can_msg_pb2._CANMSG
_LVBATTCHARGINGEVENT.fields_by_name['pre_cgw_log_info'].message_type = _PRECGWLOGINFO
DESCRIPTOR.message_types_by_name['LvBattChargingEvent'] = _LVBATTCHARGINGEVENT
DESCRIPTOR.message_types_by_name['PreCgwLogInfo'] = _PRECGWLOGINFO

LvBattChargingEvent = _reflection.GeneratedProtocolMessageType('LvBattChargingEvent', (_message.Message,), dict(
  DESCRIPTOR = _LVBATTCHARGINGEVENT,
  __module__ = 'lv_batt_charging_msg_pb2'
  # @@protoc_insertion_point(class_scope:LvBattChargingEvent)
  ))
_sym_db.RegisterMessage(LvBattChargingEvent)

PreCgwLogInfo = _reflection.GeneratedProtocolMessageType('PreCgwLogInfo', (_message.Message,), dict(
  DESCRIPTOR = _PRECGWLOGINFO,
  __module__ = 'lv_batt_charging_msg_pb2'
  # @@protoc_insertion_point(class_scope:PreCgwLogInfo)
  ))
_sym_db.RegisterMessage(PreCgwLogInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\025LvBattChargingMessage'))
# @@protoc_insertion_point(module_scope)
