# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_update_tile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_update_tile.proto',
  package='',
  serialized_pb=_b('\n\x15map_update_tile.proto\"k\n\x0fmap_update_tile\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x16\n\x0eglobal_version\x18\x02 \x01(\x05\x12\x0e\n\x06tileID\x18\x03 \x01(\x03\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x42\x37\n\"com.nextev.cvs_proto.protobuf.adasB\x11MapUpdateTileUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAP_UPDATE_TILE = _descriptor.Descriptor(
  name='map_update_tile',
  full_name='map_update_tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='map_update_tile.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='global_version', full_name='map_update_tile.global_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tileID', full_name='map_update_tile.tileID', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='map_update_tile.version', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='map_update_tile.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['map_update_tile'] = _MAP_UPDATE_TILE

map_update_tile = _reflection.GeneratedProtocolMessageType('map_update_tile', (_message.Message,), dict(
  DESCRIPTOR = _MAP_UPDATE_TILE,
  __module__ = 'map_update_tile_pb2'
  # @@protoc_insertion_point(class_scope:map_update_tile)
  ))
_sym_db.RegisterMessage(map_update_tile)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.nextev.cvs_proto.protobuf.adasB\021MapUpdateTileUnit'))
# @@protoc_insertion_point(module_scope)
