# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: occupant_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='occupant_status.proto',
  package='',
  serialized_pb=_b('\n\x15occupant_status.proto\"\xf0\x01\n\x0eOccupantStatus\x12\x46\n\x1a\x66r_le_seat_occupant_status\x18\x01 \x01(\x0e\x32\".OccupantStatus.SeatOccupantStatus\x12\x46\n\x1a\x66r_ri_seat_occupant_status\x18\x02 \x01(\x0e\x32\".OccupantStatus.SeatOccupantStatus\"N\n\x12SeatOccupantStatus\x12\x0f\n\x0bNO_OCCUPANT\x10\x00\x12\x0c\n\x08OCCUPANT\x10\x01\x12\x0c\n\x08RESERVED\x10\x02\x12\x0b\n\x07INVALID\x10\x03\x42:\n$com.nextev.cvs_proto.protobuf.customB\x12OccupantStatusUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_OCCUPANTSTATUS_SEATOCCUPANTSTATUS = _descriptor.EnumDescriptor(
  name='SeatOccupantStatus',
  full_name='OccupantStatus.SeatOccupantStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_OCCUPANT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OCCUPANT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESERVED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=188,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_OCCUPANTSTATUS_SEATOCCUPANTSTATUS)


_OCCUPANTSTATUS = _descriptor.Descriptor(
  name='OccupantStatus',
  full_name='OccupantStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fr_le_seat_occupant_status', full_name='OccupantStatus.fr_le_seat_occupant_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fr_ri_seat_occupant_status', full_name='OccupantStatus.fr_ri_seat_occupant_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OCCUPANTSTATUS_SEATOCCUPANTSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=266,
)

_OCCUPANTSTATUS.fields_by_name['fr_le_seat_occupant_status'].enum_type = _OCCUPANTSTATUS_SEATOCCUPANTSTATUS
_OCCUPANTSTATUS.fields_by_name['fr_ri_seat_occupant_status'].enum_type = _OCCUPANTSTATUS_SEATOCCUPANTSTATUS
_OCCUPANTSTATUS_SEATOCCUPANTSTATUS.containing_type = _OCCUPANTSTATUS
DESCRIPTOR.message_types_by_name['OccupantStatus'] = _OCCUPANTSTATUS

OccupantStatus = _reflection.GeneratedProtocolMessageType('OccupantStatus', (_message.Message,), dict(
  DESCRIPTOR = _OCCUPANTSTATUS,
  __module__ = 'occupant_status_pb2'
  # @@protoc_insertion_point(class_scope:OccupantStatus)
  ))
_sym_db.RegisterMessage(OccupantStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.customB\022OccupantStatusUnit'))
# @@protoc_insertion_point(module_scope)
