# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svt_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import position_status_pb2
import vehicle_status_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='svt_msg.proto',
  package='',
  serialized_pb=_b('\n\rsvt_msg.proto\x1a\x15position_status.proto\x1a\x14vehicle_status.proto\"}\n\x08SVTEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\x04\x12\x13\n\x0breason_code\x18\x05 \x01(\t\x12\x1a\n\x06status\x18\x06 \x01(\x0b\x32\n.SVTStatus\"\xff\x02\n\tSVTStatus\x12&\n\x0evehicle_status\x18\x01 \x01(\x0b\x32\x0e.VehicleStatus\x12(\n\x0fposition_status\x18\x02 \x01(\x0b\x32\x0f.PositionStatus\x12\x39\n\x11pow_supply_source\x18\x03 \x01(\x0e\x32\x1e.SVTStatus.PowSupplySourceType\x12\x1c\n\x14\x62\x61\x63kup_battery_level\x18\x04 \x01(\x02\x12\x30\n\x0egnss_ant_stats\x18\x05 \x01(\x0e\x32\x18.SVTStatus.AntennaStatus\x12\x18\n\x10\x61nti_theft_alarm\x18\x06 \x01(\x08\"9\n\x13PowSupplySourceType\x12\x0e\n\nLV_BATTERY\x10\x00\x12\x12\n\x0e\x42\x41\x43KUP_BATTERY\x10\x01\"@\n\rAntennaStatus\x12\x11\n\rSHORT_CIRCUIT\x10\x00\x12\x10\n\x0cOPEN_CIRCUIT\x10\x01\x12\n\n\x06NORMAL\x10\x02\x42\x39\n$com.nextev.cvs_proto.protobuf.eventsB\x11SVTServiceMessage')
  ,
  dependencies=[position_status_pb2.DESCRIPTOR,vehicle_status_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SVTSTATUS_POWSUPPLYSOURCETYPE = _descriptor.EnumDescriptor(
  name='PowSupplySourceType',
  full_name='SVTStatus.PowSupplySourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LV_BATTERY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_BATTERY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=450,
  serialized_end=507,
)
_sym_db.RegisterEnumDescriptor(_SVTSTATUS_POWSUPPLYSOURCETYPE)

_SVTSTATUS_ANTENNASTATUS = _descriptor.EnumDescriptor(
  name='AntennaStatus',
  full_name='SVTStatus.AntennaStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHORT_CIRCUIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_CIRCUIT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=509,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_SVTSTATUS_ANTENNASTATUS)


_SVTEVENT = _descriptor.Descriptor(
  name='SVTEvent',
  full_name='SVTEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SVTEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='SVTEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='SVTEvent.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='SVTEvent.event_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason_code', full_name='SVTEvent.reason_code', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='SVTEvent.status', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=187,
)


_SVTSTATUS = _descriptor.Descriptor(
  name='SVTStatus',
  full_name='SVTStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_status', full_name='SVTStatus.vehicle_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_status', full_name='SVTStatus.position_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pow_supply_source', full_name='SVTStatus.pow_supply_source', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backup_battery_level', full_name='SVTStatus.backup_battery_level', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gnss_ant_stats', full_name='SVTStatus.gnss_ant_stats', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anti_theft_alarm', full_name='SVTStatus.anti_theft_alarm', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SVTSTATUS_POWSUPPLYSOURCETYPE,
    _SVTSTATUS_ANTENNASTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=573,
)

_SVTEVENT.fields_by_name['status'].message_type = _SVTSTATUS
_SVTSTATUS.fields_by_name['vehicle_status'].message_type = vehicle_status_pb2._VEHICLESTATUS
_SVTSTATUS.fields_by_name['position_status'].message_type = position_status_pb2._POSITIONSTATUS
_SVTSTATUS.fields_by_name['pow_supply_source'].enum_type = _SVTSTATUS_POWSUPPLYSOURCETYPE
_SVTSTATUS.fields_by_name['gnss_ant_stats'].enum_type = _SVTSTATUS_ANTENNASTATUS
_SVTSTATUS_POWSUPPLYSOURCETYPE.containing_type = _SVTSTATUS
_SVTSTATUS_ANTENNASTATUS.containing_type = _SVTSTATUS
DESCRIPTOR.message_types_by_name['SVTEvent'] = _SVTEVENT
DESCRIPTOR.message_types_by_name['SVTStatus'] = _SVTSTATUS

SVTEvent = _reflection.GeneratedProtocolMessageType('SVTEvent', (_message.Message,), dict(
  DESCRIPTOR = _SVTEVENT,
  __module__ = 'svt_msg_pb2'
  # @@protoc_insertion_point(class_scope:SVTEvent)
  ))
_sym_db.RegisterMessage(SVTEvent)

SVTStatus = _reflection.GeneratedProtocolMessageType('SVTStatus', (_message.Message,), dict(
  DESCRIPTOR = _SVTSTATUS,
  __module__ = 'svt_msg_pb2'
  # @@protoc_insertion_point(class_scope:SVTStatus)
  ))
_sym_db.RegisterMessage(SVTStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\021SVTServiceMessage'))
# @@protoc_insertion_point(module_scope)
