# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PUS_ctrl_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PUS_ctrl_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16PUS_ctrl_message.proto\"\xa0\x01\n\x0c\x43TRL_MESSAGE\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x1d\n\tctrl_type\x18\x04 \x01(\x0e\x32\n.CTRL_TYPE\x12\x0e\n\x06\x63md_id\x18\x05 \x01(\x0c\x12\x10\n\x08req_args\x18\x06 \x03(\x0c\x12\x10\n\x08rep_args\x18\x07 \x03(\x0c\x12\x0e\n\x06req_id\x18\x08 \x01(\x0c*\x1d\n\tCTRL_TYPE\x12\x07\n\x03REQ\x10\x00\x12\x07\n\x03REP\x10\x01\x62\x06proto3')
)

_CTRL_TYPE = _descriptor.EnumDescriptor(
  name='CTRL_TYPE',
  full_name='CTRL_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQ', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=189,
  serialized_end=218,
)
_sym_db.RegisterEnumDescriptor(_CTRL_TYPE)

CTRL_TYPE = enum_type_wrapper.EnumTypeWrapper(_CTRL_TYPE)
REQ = 0
REP = 1



_CTRL_MESSAGE = _descriptor.Descriptor(
  name='CTRL_MESSAGE',
  full_name='CTRL_MESSAGE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='CTRL_MESSAGE.device', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='CTRL_MESSAGE.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CTRL_MESSAGE.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctrl_type', full_name='CTRL_MESSAGE.ctrl_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd_id', full_name='CTRL_MESSAGE.cmd_id', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_args', full_name='CTRL_MESSAGE.req_args', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rep_args', full_name='CTRL_MESSAGE.rep_args', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_id', full_name='CTRL_MESSAGE.req_id', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=187,
)

_CTRL_MESSAGE.fields_by_name['ctrl_type'].enum_type = _CTRL_TYPE
DESCRIPTOR.message_types_by_name['CTRL_MESSAGE'] = _CTRL_MESSAGE
DESCRIPTOR.enum_types_by_name['CTRL_TYPE'] = _CTRL_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CTRL_MESSAGE = _reflection.GeneratedProtocolMessageType('CTRL_MESSAGE', (_message.Message,), {
  'DESCRIPTOR' : _CTRL_MESSAGE,
  '__module__' : 'PUS_ctrl_message_pb2'
  # @@protoc_insertion_point(class_scope:CTRL_MESSAGE)
  })
_sym_db.RegisterMessage(CTRL_MESSAGE)


# @@protoc_insertion_point(module_scope)
