cmdopt: stg
host:
  tsp: https://tsp-stg.nio.com
  tsp_ex: https://tsp-stg.nio.com
  tsp_in: https://tsp-stg.nioint.com
  v_in_4430: https://v-stg.nioint.com:4430
  adc_ex_4430: https://tsp-adc-stg.nio.com:4430
  vms: https://tsp-vms-stg.nio.com
  lifestyle: https://app-stg.nio.com
  mock: http://10.110.3.103:5000
  app: https://app-stg.nio.com
  app_ex: https://app-stg.nio.com
  app_in: https://app-stg.nioint.com
  msg_ex: https://msg-stg.nio.com
  msg_in: https://msg-stg.nioint.com
  app_tob_in: https://app-tob-stg.nioint.com
  gis_in: https://gis-stg.nioint.com
  uds_in: http://uds-stg.nioint.com
  phoenix_ex: https://phoenix-datalogger-stg.nio.com
message:
  host: tsp-nmp-stg.nioint.com
  port: 20083
  host_public: tsp-nmp-stg.nio.com
  port_public: 20084
kafka:
  comn:
    bootstrap.servers:
      - swc-common-kafka00-stg.nioint.com:9092
      - swc-common-kafka01-stg.nioint.com:9092
      - swc-common-kafka02-stg.nioint.com:9092
    group.id: ev_monitor_test
    auto.offset.reset: latest
    security.protocol: sasl_plaintext
    sasl.mechanisms: PLAIN
    sasl.username: MQkcWVlK2Ijy
    sasl.password: gernCmuEnqgW
    enable.partition.eof: False
    topics:
      vehicle_data: swc-tsp-data_collection-stg-vehicle_data
      ecall: swc-cvs-tsp-stg-80001-ecall
      power_swap: swc-cvs-tsp-stg-80001-power_swap
      wti_can_signal: swc-cvs-tsp-stg-80001-wti_can_signal # 下游SCR电池告警系统消费
      charging: swc-cvs-tsp-stg-80001-charging # 充电信息下游PE（Power Express）消费
      admin_change: swc-tsp-poseidon-stg-80001-admin_change #推送主用车人变更等信息。possedon，UDS消费
      vehicle_notification: swc-cvs-tsp-stg-80001-hermes-vehicle_status_notification # 下游有NSC（NIO Service Cloud）Morgan系统，消费车辆低电量提醒信息 ，推送到APP Msg，最终发送短信和App消息提醒
      bms_config: swc-cvs-tsp-stg-80001-bms-config # 电池管理系统Bamboo
      fod: swc-cvs-tsp-stg-80001-fod # Mercury、Artemis、VINBOM
      bms_msg: swc-tsp-data_collection-stg-bms_can_msg
      owner_change: swc-cvs-tsp-stg-80001-owner-change # PowerNorth权益需求
      green_dragon: swc-cvs-tsp-stg-80001-green-dragon # 转发绿龙相关事件
      ignite: swc-cvs-tsp-stg-80001-hermes-ignite_notification
  cvs:
    bootstrap.servers:
      - cvs-kafka01-stg.nioint.com:9092
      - cvs-kafka02-stg.nioint.com:9092
      - cvs-kafka03-stg.nioint.com:9092
    group.id: ev_monitor_test
    auto.offset.reset: latest
    security.protocol: sasl_plaintext
    sasl.mechanisms: PLAIN
    sasl.username: mv5ET4yB379G
    sasl.password: X84vUQotCzNT
    enable.partition.eof: False
    topics:
      cgw: swc-cvs-nmp-stg_tsp-10005-client_status
      cdc: swc-cvs-nmp-stg-30007-client_status
      adc: swc-cvs-nmp-stg_tsp-10107-client_status
      data_report: swc-cvs-nmp-stg_tsp-10005-data_report
      data_report_periodical: swc-cvs-nmp-dev_tsp-10005-data_report_periodical
      alarm_reported: swc-tsp-evm-stg-alarm_signals_reported # evm sever上报告警到国家平台后，slytherin 会消费它更新history_wti_alarm表
      push_event: swc-cvs-tsp-stg-80001-push_event # hermes消费该topic推送通知给手机，例如svt，specific的下雨未关窗
      bcu_07: swc-tsp-data_collection-stg-can_msg
      push_email: swc-cvs-nmp-cn-stg-push-email # app_message邮件推送
      push_mi: swc-cvs-nmp-cn-stg-push-mi # app_message小米推送
      push_apns: swc-cvs-nmp-cn-stg-push-apns # app_message苹果推送
      push_hw: swc-cvs-nmp-cn-stg-push-hw # app_message华为推送
      push_fcm: swc-cvs-nmp-cn-stg-push-fcm # app_message谷歌推送
      push_sms: swc-cvs-nmp-cn-stg-push-sms # 短信推送
      push_feishu: swc-cvs-nmp-cn-stg-push-feishu # 飞书推送
  adas:
    bootstrap.servers:
      - 10.128.242.151:9092
      - 10.128.243.164:9092
      - 10.128.243.6:9092
    group.id: ev_monitor_test
    auto.offset.reset: latest
    security.protocol: sasl_plaintext
    sasl.mechanisms: PLAIN
    sasl.username: LKNw1JFwenLK
    sasl.password: ijd5nK6wLmeII
    enable.partition.eof: False
    topics:
      data_report_10107: swc-adas-nmp-stg_tsp-10107-data_report # np数据。slyther消费


cassandra:
  datacollection:
    nodes:
      - 10.128.237.39
      - 10.128.236.230
      - 10.128.239.173
    port: 9042
    keyspace: data_collection_stg
    user: tsp_stg_r
    password: Ne6K8pu2CSgixto3cnnFWmZ9
  evm:
    nodes:
      - 10.128.237.39
      - 10.128.236.230
      - 10.128.239.173
    port: 9042
    keyspace: ev_monitoring_stg
    user: tsp_stg_r
    password: Ne6K8pu2CSgixto3cnnFWmZ9

mysql:
  rvs:
    host: swc-rds-tsp-master-stg.nioint.com
    port: 3306
    user: tsp_stg_r
    password: Y2YzOTcy
    database: remote_vehicle_staging
    autocommit: True
    cursorclass: pymysql.cursors.DictCursor
    charset: utf8mb4
    retry_num: 60
  sharding:
    host: swc-rds-tsp-master-stg.nioint.com
    port: 3306
    user: tsp_stg_r
    password: Y2YzOTcy
    database: tsp_sharding_staging
    autocommit: True
    charset: utf8mb4
    retry_num: 60
  rvs_data:
    host: swc-rds-tsp-master-stg.nioint.com
    port: 3306
    user: tsp_stg_r
    password: Y2YzOTcy
    database: rvs_data_stg
    autocommit: True
    cursorclass: pymysql.cursors.DictCursor
    charset: utf8mb4
    retry_num: 60
  #  vms:
  #    # 未验证
  #    host: s-awsbj-tsp-01.cw00om4rxgzj.rds.cn-north-1.amazonaws.com.cn
  #    port: 3306
  #    user: tsp_stg_r
  #    password: Y2YzOTcy
  #    database: vms_test
  #    autocommit: True
  #    cursorclass: pymysql.cursors.DictCursor
  #    charset: utf8mb4
  #  fota:
  #    # 未验证
  #    host: 10.112.12.65
  #    user: test-team
  #    passwd: tes123
  #    db: fota-ver
  #  statistics:
  #    host: swc-rds-vms-master-stg.nioint.com
  #    port: 3306
  #    user: tsp_test_s_r
  #    password: qA4bD8QsaOpwwQHE09N
  #    database: vehicle_data_statistics_staging
  #    SSH_host: 10.128.245.27
  #    SSH_user: your_user_name
  #    SSH_key: path_of_your_private_key
  #    SSH_port: 2222

  # 需要走跳板机
  nmp:
    host: swc-rds-tsp-master-stg.nioint.com
    port: 3306
    user: tsp_stg_r
    password: Y2YzOTcy
    database: message_staging_tsp
    autocommit: True
    charset: utf8mb4
    retry_num: 60
  nmp_app:
    host: swc-rds-cs-master-stg.nioint.com
    port: 3306
    user: user_message
    password: gzNw1ZNehIY
    database: message_staging_new
    autocommit: True
    cursorclass: pymysql.cursors.DictCursor
    charset: utf8mb4
    retry_num: 60
    jump_machine: jump
  nmp_app_tob:
    host: swc-rds-cs-master-stg.nioint.com
    port: 3306
    user: app_msg_tob_staging_rw
    password: D4Q8DM44iqRIg8MPOSj
    database: app_msg_tob_staging
    autocommit: True
    cursorclass: pymysql.cursors.DictCursor
    charset: utf8mb4
    retry_num: 60
    jump_machine: jump
  #
  #  # 需要走跳板机
  #  data_stat:
  #    host: swc-rds-vms-master-stg.nioint.com
  #    port: 3306
  #    user: tsp_test_s_r
  #    password: qA4bD8QsaOpwwQHE09N
  #    database: vehicle_data_statistics_staging
  #    autocommit: True
  #    cursorclass: pymysql.cursors.DictCursor
  #    charset: utf8mb4
  battery_trace:
    host: swc-rds-tsp-master-stg.nioint.com
    port: 3306
    user: tsp_stg_r
    password: Y2YzOTcy
    database: battery_trace_staging
    autocommit: True
    cursorclass: pymysql.cursors.DictCursor
    charset: utf8mb4
    retry_num: 60

mongodb:
  rvs:
    username: r_v_stg_auto
    password: Id9fPYjNl2dzHfnhekT
    host: 10.128.234.72
    port: 27017
    database: remote_vehicle_stg

redis:
  datacollection:
    host: s-tsp-message-01.dyebgy.0001.cnn1.cache.amazonaws.com.cn
    port: 6379
  cluster:
    nodes: [ { host: tsp-cluster-cache-stg.nioint.com, port: 6379 } ]
  message:
    host: s-bj-cs-message-01.dyebgy.0001.cnn1.cache.amazonaws.com.cn # 需要跳板机
    port: 6379

vehicles:
  register_client:
    NT1:
      v1:
        vid: 03931ed31ce0441a9f94874f23cb9b09
        vin: SQETEST0117977909
        10005_client: ChAaMjGnyl3PvDlO4mtuA1VUEAEY3-YcIJVOKAI=
        10107_client: ChC3Hjvyip2Kx8Qn-4cN0EPsEAEY_OYcIPtOKAI=
      v2:
        vid: ab7e2766ee094455847401e51d7f83bf
        vin: SQETEST0329461931
        10005_client: ChCa7YFOO8YkvZCzeAUKt0D2EAEY_eYcIJVOKAI=
        10107_client: ChD0weBb1Nxw1Z-d76-_M_9nEAEY_uYcIPtOKAI=
    NT2:
      v1:
        vid: cf5c0fac765944b78062387c654d07da
        vin: SQETEST0522398453
        10005_client: ChBcOWAVqB_Dddw-NAElOHN_EAEY-OYcIJVOKAI=
        100512_client: ChBjB59XnrOPq_77m6oYdoeBEAEY--YcIKCRBigC
      v2:
        vid: 81299aea279e422da9a039340d490a41
        vin: SQETEST0344996631
        10005_client: ChCRiKFIfQ_XWjbj6dMMrirZEAEYhOocIJVOKAI=
        100512_client: ChAhYqJK1qK88X6psj-A_XaKEAEYheocIKCRBigC
  normal:
    #    vehicle_id: 895f1025201041fca4f6fda51ba672c6
    #    client_id: "ChBknvw9SWO2LZIqIOIKzcq5EAEYsZ4cIJVOKAI="
    #    cdc_client_id: "ChAeUWbovx55BlUkj73nQgKGEAEYvcx4ILfqASgB"
    #    vin: SQETEST0677602364
    #    phone: 98762489622
    #    phone_code: 229670
    #    account_id: 182603460
    vehicle_id: 996aad41030c4291813516a236dbee6d
    client_id: "ChDMrG_fqcmQ1CwFDdFFfZ60EAEY0g8glU4oAg=="
    cdc_client_id: "ChAeUWbovx55BlUkj73nQgKGEAEYvcx4ILfqASgB"
    vin: SQEHUT15905152530
    phone: 98762486907
    phone_code: 120336
    account_id: 125697180
  nmp:
    vehicle_id: a2d883247f3c4339a120b559b9c0818e
    client_id: "ChBbbp96rqR_8Q67vUys1_q2EAEY2eQPIJVOKAI="
    vin: SQETEST0759725270
    account_id: 730795298
    phone: 98762487028
    phone_code: 838799
    #    token_10000: "Bearer 2.01dxWJ8LNIPVK3r52xNw6lQ/nE80YFz6uqSrb+yUAUP0="
    token_10001: "Bearer 2.0Gbi8z9s3XkDQEFhZmq6t7TESopZ/PyXUERLBRwkE8oE="
    #    token_10002: "Bearer 2.0vVaEeCsXwM+B94t4OqWdgKzgt5UCW20yq32b9NvbSNY="
    #    token_80001: "Bearer 2.097vYoJCCG7zN12MIPKLGEGIH49hq4G0dGSyGXdak5CE="
    client_id_app_10001_old: "ChB34gFkTdnbEibvcnb6xTDIEAEYgaZ7IJFOKAE="
    client_id_app_10001: "ChBh7BtOI8g0qFlmULdDN08lEAEYg7l7IJFOKAE="
    device_id_app: "45895a7c65521c96"
  nmp_bvt:
    vehicle_id: d01fdd64c8dd47e08b4290a5f98c596c
    client_id: "ChAqB0Uj23Af_3Np3EEgJtJSEAEYsp4cIJVOKAI="
    vin: SQETEST0678117278
    account_id: 118293111
    phone: 98762489623
    phone_code: 810525
    client_id_app_10001: "ChAh2iwc512ROv_A2gTF87gGEAEYpM97IJFOKAE="
    device_id_app: "45895a7c65521c96"

nmp_app:
  account_id: 118293111
  phone: 98762489623
  vc_code: 810525

push_sms:
  user_id: 687145
  account_id: 242222849
  recipient: '+8617610551933'
app_message_keeper:
  nmp_app:
    10001: # ANDROID_NIO_APP
      user1:
        update_client_id: ChCCUjnqgmx2QY1rGpUHzUN-EAEYz6CAASCRTigB
        bind_client_id: ChClh5IENgMmWKXidR074eFvEAEY0r-XASCRTigB
        account_id: 288908977
        mobile: 98762545868
        vc_code: 345382
      user2:
        account_id: 262253659
        mobile: 98762767474
        vc_code: 523053
    10002: # IOS_NIO_APP
      user1:
        update_client_id: ChC0npzpKLhEFiJXRRRth1PWEAEY-7-XASCSTigA
        bind_client_id: ChBk7S-khuCcDiGAtqoCwOGeEAEY06CAASCSTigA
        account_id: 415220827
        mobile: 98762545870
        vc_code: 777678
      user2:
        account_id: 427361345
        mobile: 98762767476
        vc_code: 163613
  nmp_app_tob:
    10003: # Staff APP register client
      user1:
        update_client_id: ChCmLjULApzr3ChtZkf2OWxMEAEYDyCTTigB
        bind_client_id: ChCRA82y2Lt27SDKLFAqEsr8EAEYDSCTTigB
        account_id: 136635060
        mobile: 98762519910
        vc_code: 201089
      user2:
        account_id: 90385217
        mobile: 98762519911
        vc_code: 950770
    10018: # Fellow APP register client
      user1:
        update_client_id: ChCNZ0veYnCDKZsd-UvN_X0BEAEYECCiTigB
        bind_client_id: ChDMEJ3_h7xRLFIW5SvdXwrREAEYDiCiTigB
        account_id: 259138155
        mobile: 98762519912
        vc_code: 762691
      user2:
        account_id: 221463409
        mobile: 98762519913
        vc_code: 783096

secret:
  10000: acbd18db4cc2f85cedef654fccc4a4d8
  10001: 4AE54A0CF4C8B3E4f3E0d24C34A42068
  10002: 2bc9b00fdcf8f7ded6d77afdd7077e79
  10003: f174b769ad18af17c0f65b83214ac0cc
  10004: 7936e30cb1b8948ac2f283871642029c
  10005: b207319e51865e85e01c15cb29804b55
  10006: 68f828215165cd42cab37e8643a00019
  10007: ae108a49688ab8b87f392b452d43829e
  10008: 4cfdb3115a617a508ef584f896c08133
  10010: 2ab59bd6192acb105f0f5c254ef55443
  10011: d52afaba16414c0f845dae70b4f8ac79
  10012: f49e94b0f390ef210bd9eeee823d746a
  10013: 33a130f9425063421cd9e7b6ed6050a5
  10014: 6396c6d430dd48809fea88fb01d94cce
  10016: cbaa22028ddd4b169e4ce452a3138afd
  10018: 9a429afaf2044c51b0cc3cda8cfd5a89
  10022: 2f1f42e22ea484b2f9db2049540066c0
  10023: 18aca711d33d5c318a9ade7b22a3d341
  10024: 012b025c58c14adbb67ae14c1f5d854c
  10066: 0ca7836511d143279a0ec04773c4b19b
  10102: 5e725e3d9a5c4b579275903f91682f04
  10107: 32513691d40e486597f8c05eb65a7de9
  30006: 93ee15dab422478289d4def041193134
  30007: 3ca9b9c97ae94f2dacabc006d8eaad1c
  30010: 1b3424e49a4b402c9fb8a6d2dc662cb8
  50004: f911639ddc3d44bd9eaa6d21c96875b2
  80001: 689fC85e79F6Da61E039427E7176e691
  80002: fe386ea056f44149ada32fb7fa8dba66
  100002: aD6309a8082eb1c8E3371EF361AaCd51
  100004: f990a4ce5D0d88C03b196c707c5230db
  100006: 6295f98351F04a0e575aC8e8fD6e1Bde
  100008: bD6f916F622aBecF77d638E485A1B2f4
  100024: A8f7cF54A8322129A800190a471eAEA8
  100034: c4A26BF73b79d87FE7b7F2D46562EE48
  100055: 98d0fdf3000b2e7dd87cFC821791c9f0
  100105: 3B1b5ef9df2d4a019d69Fc5fb0638a7D
  100159: 8f95def9cc84a6428c64e21fc4efa344
  100423: dd35E1229a61747824Fcd0d8b0a58aee
  100078: 837016E157CAeFcbFd1966A8D03213FE
  100480: 2f4dd0361F4a78a290c6f00F720b2294
  100512: 696433D71723ba795e07550620a60D4b
  100557: 2d51957f0aD29E58FC0A6e63ddcf6ee3