# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adas_header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adas_header.proto',
  package='',
  serialized_pb=_b('\n\x11\x61\x64\x61s_header.proto\"\xf9\x07\n\nAdasHeader\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x14\n\x0cvehicle_type\x18\x02 \x01(\r\x12\x16\n\x0e\x61\x64\x63_git_branch\x18\x03 \x01(\t\x12\x16\n\x0e\x61\x64\x63_git_commit\x18\x04 \x01(\t\x12\x18\n\x10proto_git_commit\x18\x05 \x01(\t\x12/\n\rvehicle_state\x18\x06 \x01(\x0e\x32\x18.AdasHeader.VehicleState\x12\x0f\n\x07mileage\x18\x07 \x01(\r\x12\x15\n\rvehicle_speed\x18\x08 \x01(\x02\x12\x10\n\x08yaw_rate\x18\t \x01(\x02\x12\x16\n\x0esteering_angle\x18\n \x01(\x02\x12\x1c\n\x14steering_angle_speed\x18\x0b \x01(\x02\x12\x1a\n\x12\x61\x63\x63_pedal_position\x18\x0c \x01(\x02\x12\x38\n\x12\x62rake_pedal_status\x18\r \x01(\x0e\x32\x1c.AdasHeader.BrakePedalStatus\x12\x16\n\x0e\x62rake_pressure\x18\x0e \x01(\x02\x12\x31\n\x0eturn_indicator\x18\x0f \x01(\x0e\x32\x19.AdasHeader.TurnIndicator\x12\x15\n\rgps_longitude\x18\x10 \x01(\x01\x12\x14\n\x0cgps_latitude\x18\x11 \x01(\x01\x12\x13\n\x0bgps_heading\x18\x12 \x01(\x02\x12\x12\n\ngps_status\x18\x13 \x01(\r\x12\x10\n\x08gps_hdop\x18\x14 \x01(\x02\x12\x15\n\rtrip_odometer\x18\x15 \x01(\x02\"\xa3\x01\n\x0cVehicleState\x12\x18\n\x14VEHICLE_STATE_PARKED\x10\x00\x12 \n\x1cVEHICLE_STATE_DRIVER_PRESENT\x10\x01\x12\x19\n\x15VEHICLE_STATE_DRIVING\x10\x02\x12!\n\x1dVEHICLE_STATE_SOFTWARE_UPDATE\x10\x03\x12\x19\n\x15VEHICLE_STATE_INVALID\x10\x0f\"\x97\x01\n\x10\x42rakePedalStatus\x12\"\n\x1e\x42RAKE_PEDAL_STATUS_NOT_PRESSED\x10\x00\x12\x1e\n\x1a\x42RAKE_PEDAL_STATUS_PRESSED\x10\x01\x12\x1f\n\x1b\x42RAKE_PEDAL_STATUS_RESERVED\x10\x02\x12\x1e\n\x1a\x42RAKE_PEDAL_STATUS_INVALID\x10\x03\"w\n\rTurnIndicator\x12\x17\n\x13TURN_INDICATOR_NONE\x10\x00\x12\x17\n\x13TURN_INDICATOR_LEFT\x10\x01\x12\x18\n\x14TURN_INDICATOR_RIGHT\x10\x02\x12\x1a\n\x16TURN_INDICATOR_INVALID\x10\x03\x42\x34\n\"com.nextev.cvs_proto.protobuf.adasB\x0e\x41\x64\x61sHeaderUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ADASHEADER_VEHICLESTATE = _descriptor.EnumDescriptor(
  name='VehicleState',
  full_name='AdasHeader.VehicleState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_STATE_PARKED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_STATE_DRIVER_PRESENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_STATE_DRIVING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_STATE_SOFTWARE_UPDATE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_STATE_INVALID', index=4, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=601,
  serialized_end=764,
)
_sym_db.RegisterEnumDescriptor(_ADASHEADER_VEHICLESTATE)

_ADASHEADER_BRAKEPEDALSTATUS = _descriptor.EnumDescriptor(
  name='BrakePedalStatus',
  full_name='AdasHeader.BrakePedalStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BRAKE_PEDAL_STATUS_NOT_PRESSED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRAKE_PEDAL_STATUS_PRESSED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRAKE_PEDAL_STATUS_RESERVED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRAKE_PEDAL_STATUS_INVALID', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=767,
  serialized_end=918,
)
_sym_db.RegisterEnumDescriptor(_ADASHEADER_BRAKEPEDALSTATUS)

_ADASHEADER_TURNINDICATOR = _descriptor.EnumDescriptor(
  name='TurnIndicator',
  full_name='AdasHeader.TurnIndicator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TURN_INDICATOR_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TURN_INDICATOR_LEFT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TURN_INDICATOR_RIGHT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TURN_INDICATOR_INVALID', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=920,
  serialized_end=1039,
)
_sym_db.RegisterEnumDescriptor(_ADASHEADER_TURNINDICATOR)


_ADASHEADER = _descriptor.Descriptor(
  name='AdasHeader',
  full_name='AdasHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='AdasHeader.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_type', full_name='AdasHeader.vehicle_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc_git_branch', full_name='AdasHeader.adc_git_branch', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc_git_commit', full_name='AdasHeader.adc_git_commit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proto_git_commit', full_name='AdasHeader.proto_git_commit', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_state', full_name='AdasHeader.vehicle_state', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mileage', full_name='AdasHeader.mileage', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_speed', full_name='AdasHeader.vehicle_speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_rate', full_name='AdasHeader.yaw_rate', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steering_angle', full_name='AdasHeader.steering_angle', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steering_angle_speed', full_name='AdasHeader.steering_angle_speed', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_pedal_position', full_name='AdasHeader.acc_pedal_position', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brake_pedal_status', full_name='AdasHeader.brake_pedal_status', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brake_pressure', full_name='AdasHeader.brake_pressure', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turn_indicator', full_name='AdasHeader.turn_indicator', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_longitude', full_name='AdasHeader.gps_longitude', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_latitude', full_name='AdasHeader.gps_latitude', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_heading', full_name='AdasHeader.gps_heading', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_status', full_name='AdasHeader.gps_status', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_hdop', full_name='AdasHeader.gps_hdop', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trip_odometer', full_name='AdasHeader.trip_odometer', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADASHEADER_VEHICLESTATE,
    _ADASHEADER_BRAKEPEDALSTATUS,
    _ADASHEADER_TURNINDICATOR,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=1039,
)

_ADASHEADER.fields_by_name['vehicle_state'].enum_type = _ADASHEADER_VEHICLESTATE
_ADASHEADER.fields_by_name['brake_pedal_status'].enum_type = _ADASHEADER_BRAKEPEDALSTATUS
_ADASHEADER.fields_by_name['turn_indicator'].enum_type = _ADASHEADER_TURNINDICATOR
_ADASHEADER_VEHICLESTATE.containing_type = _ADASHEADER
_ADASHEADER_BRAKEPEDALSTATUS.containing_type = _ADASHEADER
_ADASHEADER_TURNINDICATOR.containing_type = _ADASHEADER
DESCRIPTOR.message_types_by_name['AdasHeader'] = _ADASHEADER

AdasHeader = _reflection.GeneratedProtocolMessageType('AdasHeader', (_message.Message,), dict(
  DESCRIPTOR = _ADASHEADER,
  __module__ = 'adas_header_pb2'
  # @@protoc_insertion_point(class_scope:AdasHeader)
  ))
_sym_db.RegisterMessage(AdasHeader)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.nextev.cvs_proto.protobuf.adasB\016AdasHeaderUnit'))
# @@protoc_insertion_point(module_scope)
