# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attach_file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attach_file.proto',
  package='',
  serialized_pb=_b('\n\x11\x61ttach_file.proto\"\x1d\n\x08\x46ileInfo\x12\x11\n\tfile_path\x18\x01 \x03(\tB/\n!com.nextev.cvs_proto.protobuf.rvsB\nAttachFile')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='FileInfo.file_path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), dict(
  DESCRIPTOR = _FILEINFO,
  __module__ = 'attach_file_pb2'
  # @@protoc_insertion_point(class_scope:FileInfo)
  ))
_sym_db.RegisterMessage(FileInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.nextev.cvs_proto.protobuf.rvsB\nAttachFile'))
# @@protoc_insertion_point(module_scope)
