# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: did_resp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import did_data_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='did_resp.proto',
  package='',
  serialized_pb=_b('\n\x0e\x64id_resp.proto\x1a\x0e\x64id_data.proto\"+\n\rDIDStatusResp\x12\x1a\n\x08\x64id_data\x18\x01 \x03(\x0b\x32\x08.DIDDataB5\n$com.nextev.cvs_proto.protobuf.customB\rDIDStatusUnit')
  ,
  dependencies=[did_data_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIDSTATUSRESP = _descriptor.Descriptor(
  name='DIDStatusResp',
  full_name='DIDStatusResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='did_data', full_name='DIDStatusResp.did_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=77,
)

_DIDSTATUSRESP.fields_by_name['did_data'].message_type = did_data_pb2._DIDDATA
DESCRIPTOR.message_types_by_name['DIDStatusResp'] = _DIDSTATUSRESP

DIDStatusResp = _reflection.GeneratedProtocolMessageType('DIDStatusResp', (_message.Message,), dict(
  DESCRIPTOR = _DIDSTATUSRESP,
  __module__ = 'did_resp_pb2'
  # @@protoc_insertion_point(class_scope:DIDStatusResp)
  ))
_sym_db.RegisterMessage(DIDStatusResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.customB\rDIDStatusUnit'))
# @@protoc_insertion_point(module_scope)
