# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlb_upload_switch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlb_upload_switch.proto',
  package='',
  serialized_pb=_b('\n\x17\x64lb_upload_switch.proto\"\xad\x01\n\x0f\x44lbUploadSwitch\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x64\x63_version\x18\x02 \x01(\t\x12\x1a\n\x12utc_nano_timestamp\x18\x03 \x01(\x03\x12\x12\n\nvehicle_id\x18\x04 \x01(\t\x12\x14\n\x0cvehicle_type\x18\x05 \x01(\t\x12\x16\n\x0e\x66ile_whitelist\x18\x06 \x01(\t\x12\x19\n\x11message_whitelist\x18\x07 \x01(\tB9\n\"com.nextev.cvs_proto.protobuf.adasB\x13\x44lbUploadSwitchUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DLBUPLOADSWITCH = _descriptor.Descriptor(
  name='DlbUploadSwitch',
  full_name='DlbUploadSwitch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='DlbUploadSwitch.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc_version', full_name='DlbUploadSwitch.adc_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='utc_nano_timestamp', full_name='DlbUploadSwitch.utc_nano_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_id', full_name='DlbUploadSwitch.vehicle_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_type', full_name='DlbUploadSwitch.vehicle_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_whitelist', full_name='DlbUploadSwitch.file_whitelist', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_whitelist', full_name='DlbUploadSwitch.message_whitelist', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['DlbUploadSwitch'] = _DLBUPLOADSWITCH

DlbUploadSwitch = _reflection.GeneratedProtocolMessageType('DlbUploadSwitch', (_message.Message,), dict(
  DESCRIPTOR = _DLBUPLOADSWITCH,
  __module__ = 'dlb_upload_switch_pb2'
  # @@protoc_insertion_point(class_scope:DlbUploadSwitch)
  ))
_sym_db.RegisterMessage(DlbUploadSwitch)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.nextev.cvs_proto.protobuf.adasB\023DlbUploadSwitchUnit'))
# @@protoc_insertion_point(module_scope)
