# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gd_system_information_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gd_system_information_msg.proto',
  package='',
  serialized_pb=_b('\n\x1fgd_system_information_msg.proto\"\xaf\x01\n\x18GDSystemInformationEvent\x12\x11\n\tsample_ts\x18\x01 \x01(\x04\x12\x16\n\x0emon_window_sec\x18\x02 \x01(\x05\x12=\n\x0esys_info_items\x18\x03 \x03(\x0b\x32%.GDSystemInformationEvent.SysInfoItem\x1a)\n\x0bSysInfoItem\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tBB\n$com.nextev.cvs_proto.protobuf.eventsB\x1aGDSystemInformationMessage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GDSYSTEMINFORMATIONEVENT_SYSINFOITEM = _descriptor.Descriptor(
  name='SysInfoItem',
  full_name='GDSystemInformationEvent.SysInfoItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GDSystemInformationEvent.SysInfoItem.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='GDSystemInformationEvent.SysInfoItem.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=211,
)

_GDSYSTEMINFORMATIONEVENT = _descriptor.Descriptor(
  name='GDSystemInformationEvent',
  full_name='GDSystemInformationEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='GDSystemInformationEvent.sample_ts', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mon_window_sec', full_name='GDSystemInformationEvent.mon_window_sec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sys_info_items', full_name='GDSystemInformationEvent.sys_info_items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GDSYSTEMINFORMATIONEVENT_SYSINFOITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=211,
)

_GDSYSTEMINFORMATIONEVENT_SYSINFOITEM.containing_type = _GDSYSTEMINFORMATIONEVENT
_GDSYSTEMINFORMATIONEVENT.fields_by_name['sys_info_items'].message_type = _GDSYSTEMINFORMATIONEVENT_SYSINFOITEM
DESCRIPTOR.message_types_by_name['GDSystemInformationEvent'] = _GDSYSTEMINFORMATIONEVENT

GDSystemInformationEvent = _reflection.GeneratedProtocolMessageType('GDSystemInformationEvent', (_message.Message,), dict(

  SysInfoItem = _reflection.GeneratedProtocolMessageType('SysInfoItem', (_message.Message,), dict(
    DESCRIPTOR = _GDSYSTEMINFORMATIONEVENT_SYSINFOITEM,
    __module__ = 'gd_system_information_msg_pb2'
    # @@protoc_insertion_point(class_scope:GDSystemInformationEvent.SysInfoItem)
    ))
  ,
  DESCRIPTOR = _GDSYSTEMINFORMATIONEVENT,
  __module__ = 'gd_system_information_msg_pb2'
  # @@protoc_insertion_point(class_scope:GDSystemInformationEvent)
  ))
_sym_db.RegisterMessage(GDSystemInformationEvent)
_sym_db.RegisterMessage(GDSystemInformationEvent.SysInfoItem)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\032GDSystemInformationMessage'))
# @@protoc_insertion_point(module_scope)
