# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nbs_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nbs_status.proto',
  package='',
  serialized_pb=_b('\n\x10nbs_status.proto\"\x8d\x04\n\tNBSStatus\x12\"\n\x07nbs_sts\x18\x01 \x01(\x0e\x32\x11.NBSStatus.NBSSts\x12\x12\n\nnbs_blkage\x18\x02 \x01(\x05\x12\x17\n\x0fnbs_instruction\x18\x03 \x01(\x05\x12\x18\n\x10nbs_abort_reason\x18\x04 \x01(\x05\x12\x30\n\x12nbs_blkage_frnt_le\x18\x05 \x01(\x0e\x32\x14.NBSStatus.NBSBlkage\x12\x30\n\x12nbs_blkage_frnt_ri\x18\x06 \x01(\x0e\x32\x14.NBSStatus.NBSBlkage\x12.\n\x10nbs_blkage_re_le\x18\x07 \x01(\x0e\x32\x14.NBSStatus.NBSBlkage\x12.\n\x10nbs_blkage_re_ri\x18\x08 \x01(\x0e\x32\x14.NBSStatus.NBSBlkage\"\x92\x01\n\x06NBSSts\x12\x0f\n\x0bNBS_STS_OFF\x10\x00\x12\x13\n\x0fNBS_STS_INITIAL\x10\x01\x12\x13\n\x0fNBS_STS_STANDBY\x10\x02\x12\x12\n\x0eNBS_STS_MOVING\x10\x03\x12\x11\n\rNBS_STS_ABORT\x10\x04\x12\x10\n\x0cNBS_STS_FAIL\x10\x05\x12\x14\n\x10NBS_STS_RESERVED\x10\x06\"<\n\tNBSBlkage\x12\x18\n\x14NBS_BLKAGE_NO_BLKAGE\x10\x00\x12\x15\n\x11NBS_BLKAGE_BLKAGE\x10\x01\x42\x35\n$com.nextev.cvs_proto.protobuf.customB\rNBSStatusUnit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_NBSSTATUS_NBSSTS = _descriptor.EnumDescriptor(
  name='NBSSts',
  full_name='NBSStatus.NBSSts',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_OFF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_INITIAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_STANDBY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_MOVING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_ABORT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_FAIL', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_STS_RESERVED', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=338,
  serialized_end=484,
)
_sym_db.RegisterEnumDescriptor(_NBSSTATUS_NBSSTS)

_NBSSTATUS_NBSBLKAGE = _descriptor.EnumDescriptor(
  name='NBSBlkage',
  full_name='NBSStatus.NBSBlkage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NBS_BLKAGE_NO_BLKAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NBS_BLKAGE_BLKAGE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=486,
  serialized_end=546,
)
_sym_db.RegisterEnumDescriptor(_NBSSTATUS_NBSBLKAGE)


_NBSSTATUS = _descriptor.Descriptor(
  name='NBSStatus',
  full_name='NBSStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nbs_sts', full_name='NBSStatus.nbs_sts', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_blkage', full_name='NBSStatus.nbs_blkage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_instruction', full_name='NBSStatus.nbs_instruction', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_abort_reason', full_name='NBSStatus.nbs_abort_reason', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_blkage_frnt_le', full_name='NBSStatus.nbs_blkage_frnt_le', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_blkage_frnt_ri', full_name='NBSStatus.nbs_blkage_frnt_ri', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_blkage_re_le', full_name='NBSStatus.nbs_blkage_re_le', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbs_blkage_re_ri', full_name='NBSStatus.nbs_blkage_re_ri', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NBSSTATUS_NBSSTS,
    _NBSSTATUS_NBSBLKAGE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=546,
)

_NBSSTATUS.fields_by_name['nbs_sts'].enum_type = _NBSSTATUS_NBSSTS
_NBSSTATUS.fields_by_name['nbs_blkage_frnt_le'].enum_type = _NBSSTATUS_NBSBLKAGE
_NBSSTATUS.fields_by_name['nbs_blkage_frnt_ri'].enum_type = _NBSSTATUS_NBSBLKAGE
_NBSSTATUS.fields_by_name['nbs_blkage_re_le'].enum_type = _NBSSTATUS_NBSBLKAGE
_NBSSTATUS.fields_by_name['nbs_blkage_re_ri'].enum_type = _NBSSTATUS_NBSBLKAGE
_NBSSTATUS_NBSSTS.containing_type = _NBSSTATUS
_NBSSTATUS_NBSBLKAGE.containing_type = _NBSSTATUS
DESCRIPTOR.message_types_by_name['NBSStatus'] = _NBSSTATUS

NBSStatus = _reflection.GeneratedProtocolMessageType('NBSStatus', (_message.Message,), dict(
  DESCRIPTOR = _NBSSTATUS,
  __module__ = 'nbs_status_pb2'
  # @@protoc_insertion_point(class_scope:NBSStatus)
  ))
_sym_db.RegisterMessage(NBSStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.customB\rNBSStatusUnit'))
# @@protoc_insertion_point(module_scope)
