# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle_energy_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehicle_energy_msg.proto',
  package='',
  serialized_pb=_b('\n\x18vehicle_energy_msg.proto\"\x90\x01\n\x12VehicleEnergyEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tsample_ts\x18\x03 \x01(\x04\x12!\n\x0cveh_elec_cns\x18\x04 \x03(\x0b\x32\x0b.VehElecCns\x12\'\n\x12veh_elecc_cns_resd\x18\x05 \x03(\x0b\x32\x0b.VehElecCns\"f\n\nVehElecCns\x12\x12\n\nVehElecCns\x18\x01 \x01(\x02\x12\x17\n\x0fVehRemainingEyg\x18\x02 \x01(\x02\x12\x18\n\x10\x42MSCustomerUsage\x18\x03 \x01(\x02\x12\x11\n\tsample_ts\x18\x04 \x01(\x04\x42<\n$com.nextev.cvs_proto.protobuf.eventsB\x14VehicleEnergyMessage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VEHICLEENERGYEVENT = _descriptor.Descriptor(
  name='VehicleEnergyEvent',
  full_name='VehicleEnergyEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VehicleEnergyEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='VehicleEnergyEvent.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='VehicleEnergyEvent.sample_ts', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='veh_elec_cns', full_name='VehicleEnergyEvent.veh_elec_cns', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='veh_elecc_cns_resd', full_name='VehicleEnergyEvent.veh_elecc_cns_resd', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=173,
)


_VEHELECCNS = _descriptor.Descriptor(
  name='VehElecCns',
  full_name='VehElecCns',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VehElecCns', full_name='VehElecCns.VehElecCns', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VehRemainingEyg', full_name='VehElecCns.VehRemainingEyg', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BMSCustomerUsage', full_name='VehElecCns.BMSCustomerUsage', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_ts', full_name='VehElecCns.sample_ts', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=277,
)

_VEHICLEENERGYEVENT.fields_by_name['veh_elec_cns'].message_type = _VEHELECCNS
_VEHICLEENERGYEVENT.fields_by_name['veh_elecc_cns_resd'].message_type = _VEHELECCNS
DESCRIPTOR.message_types_by_name['VehicleEnergyEvent'] = _VEHICLEENERGYEVENT
DESCRIPTOR.message_types_by_name['VehElecCns'] = _VEHELECCNS

VehicleEnergyEvent = _reflection.GeneratedProtocolMessageType('VehicleEnergyEvent', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLEENERGYEVENT,
  __module__ = 'vehicle_energy_msg_pb2'
  # @@protoc_insertion_point(class_scope:VehicleEnergyEvent)
  ))
_sym_db.RegisterMessage(VehicleEnergyEvent)

VehElecCns = _reflection.GeneratedProtocolMessageType('VehElecCns', (_message.Message,), dict(
  DESCRIPTOR = _VEHELECCNS,
  __module__ = 'vehicle_energy_msg_pb2'
  # @@protoc_insertion_point(class_scope:VehElecCns)
  ))
_sym_db.RegisterMessage(VehElecCns)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.nextev.cvs_proto.protobuf.eventsB\024VehicleEnergyMessage'))
# @@protoc_insertion_point(module_scope)
